### ISSUE TITLE
docker build ERROR [4/6] RUN deno cache deps.ts    

### ISSUE THREAD

**Issue by andidol** [kishikawakatsumi/applelocalization-web#20]
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
docker build .
[+] Building 8.2s (8/10)                                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 37B                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 34B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/denoland/deno:ubuntu-1.17.1                                                                                               1.6s
 => [internal] load build context                                                                                                                                    0.0s
 => => transferring context: 996B                                                                                                                                    0.0s
 => [1/6] FROM docker.io/denoland/deno:ubuntu-1.17.1@sha256:4450f556c0fedd218d515bb41870fec3797c68efe26b9457367a521b04d56b1a                                         0.0s
 => CACHED [2/6] WORKDIR /app                                                                                                                                        0.0s
 => CACHED [3/6] COPY deps.ts .                                                                                                                                      0.0s
 => ERROR [4/6] RUN deno cache deps.ts                                                                                                                               6.5s
------                                                                                                                                                                    
 > [4/6] RUN deno cache deps.ts:                                                                                                                                          
#8 0.266 Download https://deno.land/x/oak/mod.ts                                                                                                                          
#8 0.268 Download https://deno.land/x/postgres/mod.ts                                                                                                                     
#8 0.268 Download https://deno.land/x/redis/mod.ts                                                                                                                        
#8 0.831 Warning Implicitly using latest version (v0.15.0) for https://deno.land/x/postgres/mod.ts                                                                        
#8 0.832 Download https://deno.land/x/postgres@v0.15.0/mod.ts
#8 0.835 Warning Implicitly using latest version (v10.5.1) for https://deno.land/x/oak/mod.ts
#8 0.835 Download https://deno.land/x/oak@v10.5.1/mod.ts
#8 0.860 Warning Implicitly using latest version (v0.25.4) for https://deno.land/x/redis/mod.ts
#8 0.860 Download https://deno.land/x/redis@v0.25.4/mod.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/application.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/body.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/context.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/cookies.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/deps.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/etag.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/helpers.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/httpError.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/http_server_native.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/http_server_native_request.ts
#8 1.005 Download https://deno.land/x/oak@v10.5.1/middleware.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/middleware/proxy.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/multipart.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/range.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/request.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/response.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/router.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/send.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/server_sent_event.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/testing.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/types.d.ts
#8 1.006 Download https://deno.land/x/oak@v10.5.1/util.ts
#8 1.022 Download https://deno.land/x/postgres@v0.15.0/client.ts
#8 1.022 Download https://deno.land/x/postgres@v0.15.0/client/error.ts
#8 1.022 Download https://deno.land/x/postgres@v0.15.0/connection/connection_params.ts
#8 1.022 Download https://deno.land/x/postgres@v0.15.0/pool.ts
#8 1.022 Download https://deno.land/x/postgres@v0.15.0/query/query.ts
#8 1.023 Download https://deno.land/x/postgres@v0.15.0/query/transaction.ts
#8 1.059 Download https://deno.land/x/redis@v0.25.4/command.ts
#8 1.059 Download https://deno.land/x/redis@v0.25.4/connection.ts
#8 1.059 Download https://deno.land/x/redis@v0.25.4/errors.ts
#8 1.059 Download https://deno.land/x/redis@v0.25.4/executor.ts
#8 1.060 Download https://deno.land/x/redis@v0.25.4/pipeline.ts
#8 1.060 Download https://deno.land/x/redis@v0.25.4/protocol/mod.ts
#8 1.060 Download https://deno.land/x/redis@v0.25.4/pubsub.ts
#8 1.060 Download https://deno.land/x/redis@v0.25.4/redis.ts
#8 1.060 Download https://deno.land/x/redis@v0.25.4/stream.ts
#8 1.246 Download https://deno.land/x/oak@v10.5.1/keyStack.ts
#8 1.281 Download https://deno.land/x/oak@v10.5.1/isMediaType.ts
#8 1.299 Download https://deno.land/x/oak@v10.5.1/structured_clone.ts
#8 1.313 Download https://deno.land/x/oak@v10.5.1/negotiation/mediaType.ts
#8 1.380 Download https://deno.land/std@0.131.0/bytes/mod.ts
#8 1.380 Download https://deno.land/std@0.131.0/encoding/base64.ts
#8 1.380 Download https://deno.land/std@0.131.0/http/http_status.ts
#8 1.380 Download https://deno.land/std@0.131.0/io/readers.ts
#8 1.380 Download https://deno.land/std@0.131.0/path/mod.ts
#8 1.381 Download https://deno.land/std@0.131.0/streams/conversion.ts
#8 1.381 Download https://deno.land/x/media_types@v3.0.2/mod.ts
#8 1.381 Download https://deno.land/x/path_to_regexp@v6.2.0/index.ts
#8 1.395 Download https://deno.land/x/postgres@v0.15.0/utils/deferred.ts
#8 1.395 Download https://deno.land/x/oak@v10.5.1/negotiation/charset.ts
#8 1.395 Download https://deno.land/x/oak@v10.5.1/negotiation/encoding.ts
#8 1.395 Download https://deno.land/x/oak@v10.5.1/negotiation/language.ts
#8 1.396 Download https://deno.land/x/postgres@v0.15.0/connection/message.ts
#8 1.414 Download https://deno.land/x/redis@v0.25.4/protocol/command.ts
#8 1.414 Download https://deno.land/x/redis@v0.25.4/protocol/reply.ts
#8 1.414 Download https://deno.land/x/redis@v0.25.4/protocol/types.ts
#8 1.426 Download https://deno.land/x/postgres@v0.15.0/deps.ts
#8 1.426 Download https://deno.land/x/postgres@v0.15.0/utils/utils.ts
#8 1.428 Download https://deno.land/x/redis@v0.25.4/vendor/https/deno.land/std/async/deferred.ts
#8 1.428 Download https://deno.land/x/redis@v0.25.4/vendor/https/deno.land/std/io/buffer.ts
#8 1.456 Download https://deno.land/x/oak@v10.5.1/buf_reader.ts
#8 1.456 Download https://deno.land/x/oak@v10.5.1/content_disposition.ts
#8 1.456 Download https://deno.land/x/oak@v10.5.1/headers.ts
#8 1.459 Download https://deno.land/x/oak@v10.5.1/tssCompare.ts
#8 1.465 Download https://deno.land/x/postgres@v0.15.0/query/decode.ts
#8 1.465 Download https://deno.land/x/postgres@v0.15.0/query/encode.ts
#8 1.466 Download https://deno.land/x/postgres@v0.15.0/connection/connection.ts
#8 1.480 Download https://deno.land/x/oak@v10.5.1/mediaTyper.ts
#8 1.496 Download https://deno.land/x/oak@v10.5.1/negotiation/common.ts
#8 1.570 Download https://deno.land/std@0.131.0/bytes/equals.ts
#8 1.570 Download https://deno.land/std@0.131.0/io/buffer.ts
#8 1.570 Download https://deno.land/std@0.131.0/_util/os.ts
#8 1.570 Download https://deno.land/std@0.131.0/path/_interface.ts
#8 1.570 Download https://deno.land/std@0.131.0/path/common.ts
#8 1.570 Download https://deno.land/std@0.131.0/path/glob.ts
#8 1.570 Download https://deno.land/std@0.131.0/path/posix.ts
#8 1.570 Download https://deno.land/std@0.131.0/path/separator.ts
#8 1.571 Download https://deno.land/std@0.131.0/path/win32.ts
#8 1.574 Download https://raw.githubusercontent.com/jshttp/mime-db/v1.52.0/db.json
#8 1.597 Download https://deno.land/x/postgres@v0.15.0/connection/packet.ts
#8 1.611 Download https://deno.land/std@0.130.0/io/buffer.ts
#8 1.614 Download https://deno.land/x/redis@v0.25.4/protocol/_util.ts
#8 1.628 Download https://deno.land/std@0.130.0/async/deferred.ts
#8 1.628 Download https://deno.land/std@0.114.0/async/mod.ts
#8 1.628 Download https://deno.land/std@0.114.0/bytes/mod.ts
#8 1.629 Download https://deno.land/std@0.114.0/crypto/mod.ts
#8 1.629 Download https://deno.land/std@0.114.0/datetime/mod.ts
#8 1.629 Download https://deno.land/std@0.114.0/encoding/base64.ts
#8 1.629 Download https://deno.land/std@0.114.0/encoding/hex.ts
#8 1.629 Download https://deno.land/std@0.114.0/fmt/colors.ts
#8 1.630 Download https://deno.land/std@0.114.0/io/buffer.ts
#8 1.630 Download https://deno.land/std@0.114.0/path/mod.ts
#8 1.637 Download https://deno.land/x/postgres@v0.15.0/query/decoders.ts
#8 1.637 Download https://deno.land/x/postgres@v0.15.0/query/oid.ts
#8 1.655 Download https://deno.land/x/postgres@v0.15.0/connection/auth.ts
#8 1.655 Download https://deno.land/x/postgres@v0.15.0/connection/message_code.ts
#8 1.655 Download https://deno.land/x/postgres@v0.15.0/connection/scram.ts
#8 1.825 Download https://deno.land/std@0.114.0/bytes/equals.ts
#8 1.825 Download https://deno.land/std@0.114.0/async/deadline.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/debounce.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/deferred.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/delay.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/mux_async_iterator.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/pool.ts
#8 1.826 Download https://deno.land/std@0.114.0/async/tee.ts
#8 1.826 Download https://deno.land/std@0.114.0/_util/os.ts
#8 1.826 Download https://deno.land/std@0.114.0/path/_interface.ts
#8 1.826 Download https://deno.land/std@0.114.0/path/common.ts
#8 1.827 Download https://deno.land/std@0.114.0/path/glob.ts
#8 1.827 Download https://deno.land/std@0.114.0/path/posix.ts
#8 1.827 Download https://deno.land/std@0.114.0/path/separator.ts
#8 1.827 Download https://deno.land/std@0.114.0/path/win32.ts
#8 1.828 Download https://deno.land/std@0.114.0/datetime/formatter.ts
#8 1.830 Download https://deno.land/x/postgres@v0.15.0/query/array_parser.ts
#8 1.830 Download https://deno.land/x/postgres@v0.15.0/query/types.ts
#8 1.845 Download https://deno.land/std@0.114.0/_wasm_crypto/mod.ts
#8 1.866 Download https://deno.land/std@0.131.0/_util/assert.ts
#8 1.866 Download https://deno.land/std@0.131.0/path/_constants.ts
#8 1.866 Download https://deno.land/std@0.131.0/path/_util.ts
#8 1.873 Download https://deno.land/std@0.131.0/bytes/bytes_list.ts
#8 1.873 Download https://deno.land/std@0.131.0/io/types.d.ts
#8 1.886 Download https://deno.land/std@0.130.0/_util/assert.ts
#8 1.886 Download https://deno.land/std@0.130.0/bytes/bytes_list.ts
#8 1.886 Download https://deno.land/std@0.130.0/bytes/mod.ts
#8 1.886 Download https://deno.land/std@0.130.0/io/types.d.ts
#8 1.905 Download https://deno.land/std@0.114.0/_util/assert.ts
#8 1.905 Download https://deno.land/std@0.114.0/bytes/bytes_list.ts
#8 1.905 Download https://deno.land/std@0.114.0/io/types.d.ts
#8 2.017 Download https://deno.land/std@0.114.0/path/_constants.ts
#8 2.017 Download https://deno.land/std@0.114.0/path/_util.ts
#8 2.032 Download https://deno.land/std@0.114.0/_wasm_crypto/crypto.js
#8 2.045 Download https://deno.land/std@0.114.0/datetime/tokenizer.ts
#8 2.074 Download https://deno.land/std@0.130.0/bytes/equals.ts
#8 2.226 Download https://deno.land/std@0.114.0/_wasm_crypto/crypto.wasm.js
#8 2.852 Check file:///app/deps.ts
#8 6.448 error: TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.448   async function getFile(contentType: string): Promise<[string, Deno.FsFile]> {
#8 6.448                                                                      ~~~~~~
#8 6.448     at https://deno.land/x/oak@v10.5.1/multipart.ts:186:70
#8 6.448 
#8 6.448 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.448       let file: Deno.FsFile | undefined;
#8 6.448                      ~~~~~~
#8 6.448     at https://deno.land/x/oak@v10.5.1/multipart.ts:227:22
#8 6.448 
#8 6.448 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.448 function fstat(file: Deno.FsFile): Promise<Deno.FileInfo | undefined> {
#8 6.448                           ~~~~~~
#8 6.448     at https://deno.land/x/oak@v10.5.1/etag.ts:60:27
#8 6.448 
#8 6.449 TS2551 [ERROR]: Property 'FsFile' does not exist on type 'typeof Deno'. Did you mean 'File'?
#8 6.449   if (body instanceof Deno.FsFile) {
#8 6.449                            ~~~~~~
#8 6.449     at https://deno.land/x/oak@v10.5.1/etag.ts:75:28
#8 6.449 
#8 6.449     'File' is declared here.
#8 6.449       export class File
#8 6.449                    ~~~~
#8 6.449         at asset:///lib.deno.ns.d.ts:1040:16
#8 6.449 
#8 6.449 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.449 ): Promise<[Uint8Array | Deno.FsFile, Uint8Array | FileInfo]> {
#8 6.449                               ~~~~~~
#8 6.449     at https://deno.land/x/oak@v10.5.1/send.ts:124:31
#8 6.449 
#8 6.449 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.449   let body: Uint8Array | Deno.FsFile;
#8 6.449                               ~~~~~~
#8 6.449     at https://deno.land/x/oak@v10.5.1/send.ts:125:31
#8 6.449 
#8 6.449 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.449   body: Uint8Array | Deno.FsFile,
#8 6.449                           ~~~~~~
#8 6.449     at https://deno.land/x/oak@v10.5.1/send.ts:145:27
#8 6.449 
#8 6.449 TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
#8 6.449   let body: Uint8Array | Deno.FsFile | null = null;
#8 6.449                               ~~~~~~
#8 6.449     at https://deno.land/x/oak@v10.5.1/send.ts:315:31
#8 6.449 
#8 6.449 Found 8 errors.
------
executor failed running [/bin/sh -c deno cache deps.ts]: exit code: 1
```

**Comment by kishikawakatsumi** [comment]
Probably fixed by https://github.com/kishikawakatsumi/applelocalization-web/commit/e6a970fb7d0fb0790238c24c887006165dd1c037
